version: '3.7'

services:
  server:
    build:
      context: ./eddo-backend
      dockerfile: Dockerfile
    image: vigonometry/eddo:backend
    command: /usr/src/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./eddo-backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./eddo-frontend
      dockerfile: Dockerfile
    image: vigonometry/eddo:frontend
    command: npm start
    volumes:
      - ./eddo-frontend/:/usr/app
      - ./eddo-frontend/build/:/var/www/html
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
